/* Generated By:JavaCC: Do not edit this line. LexerJJConstants.java */
package com.nexon.jsonparser.lexer;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerJJConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int INTEGER_CONSTANT = 6;
	/** RegularExpression Id. */
	int LOGIC_CONSTANT = 7;
	/** RegularExpression Id. */
	int DIGIT = 8;
	/** RegularExpression Id. */
	int COMMA = 9;
	/** RegularExpression Id. */
	int COLON = 10;
	/** RegularExpression Id. */
	int LEFT_BRACE = 11;
	/** RegularExpression Id. */
	int RIGHT_BRACE = 12;
	/** RegularExpression Id. */
	int LEFT_SQUARE = 13;
	/** RegularExpression Id. */
	int RIGHT_SQUARE = 14;
	/** RegularExpression Id. */
	int QUOTE = 15;
	/** RegularExpression Id. */
	int IDENTIFIER = 16;
	/** RegularExpression Id. */
	int LETTER = 17;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "<token of kind 5>",
			"<INTEGER_CONSTANT>", "<LOGIC_CONSTANT>", "<DIGIT>", "\",\"", "\":\"", "\"{\"", "\"}\"", "\"[\"", "\"]\"",
			"\"\\\"\"", "<IDENTIFIER>", "<LETTER>", };

}
