/* Generated By:JavaCC: Do not edit this line. LexerJJTokenManager.java */
package com.nexon.jsonparser.lexer;

/** Token Manager. */
public class LexerJJTokenManager implements LexerJJConstants {

	/** Debug output. */
	public static java.io.PrintStream debugStream = System.out;

	/** Set debug output. */
	public static void setDebugStream(java.io.PrintStream ds) {
		debugStream = ds;
	}

	private static final int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		default:
			return -1;
		}
	}

	private static final int jjStartNfa_0(int pos, long active0) {
		return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	static private int jjStopAtPos(int pos, int kind) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		return pos + 1;
	}

	static private int jjMoveStringLiteralDfa0_0() {
		switch (curChar) {
		case 34:
			return jjStopAtPos(0, 15);
		case 44:
			return jjStopAtPos(0, 9);
		case 58:
			return jjStopAtPos(0, 10);
		case 91:
			return jjStopAtPos(0, 13);
		case 93:
			return jjStopAtPos(0, 14);
		case 123:
			return jjStopAtPos(0, 11);
		case 125:
			return jjStopAtPos(0, 12);
		default:
			return jjMoveNfa_0(6, 0);
		}
	}

	static final long[] jjbitVec0 = { 0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL };

	static private int jjMoveNfa_0(int startState, int curPos) {
		int startsAt = 0;
		jjnewStateCnt = 23;
		int i = 1;
		jjstateSet[0] = startState;
		int kind = 0x7fffffff;
		for (;;) {
			if (++jjround == 0x7fffffff)
				ReInitRounds();
			if (curChar < 64) {
				long l = 1L << curChar;
				do {
					switch (jjstateSet[--i]) {
					case 6:
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 6)
								kind = 6;
							jjCheckNAdd(7);
						} else if (curChar == 45)
							jjstateSet[jjnewStateCnt++] = 16;
						break;
					case 1:
						if ((0xffffffffffffdbffL & l) != 0L)
							jjAddStates(0, 2);
						break;
					case 2:
						if ((0x2400L & l) != 0L && kind > 5)
							kind = 5;
						break;
					case 3:
						if (curChar == 10 && kind > 5)
							kind = 5;
						break;
					case 4:
						if (curChar == 13)
							jjstateSet[jjnewStateCnt++] = 3;
						break;
					case 7:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 6)
							kind = 6;
						jjCheckNAdd(7);
						break;
					case 16:
						if (curChar == 49 && kind > 7)
							kind = 7;
						break;
					case 17:
						if (curChar == 45)
							jjstateSet[jjnewStateCnt++] = 16;
						break;
					case 19:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjAddStates(3, 5);
						break;
					case 21:
						if (curChar == 36 && kind > 16)
							kind = 16;
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else if (curChar < 128) {
				long l = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 6:
						if ((0x7fffffe07fffffeL & l) != 0L) {
							if (kind > 16)
								kind = 16;
							jjCheckNAddStates(6, 8);
						}
						if ((0x4000000040L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 14;
						else if ((0x10000000100000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 10;
						else if ((0x4000000040000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 5;
						break;
					case 0:
						if ((0x200000002000L & l) != 0L)
							jjCheckNAddStates(0, 2);
						break;
					case 1:
						jjCheckNAddStates(0, 2);
						break;
					case 5:
						if ((0x2000000020L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 0;
						break;
					case 8:
						if ((0x2000000020L & l) != 0L && kind > 7)
							kind = 7;
						break;
					case 9:
						if ((0x20000000200000L & l) != 0L)
							jjCheckNAdd(8);
						break;
					case 10:
						if ((0x4000000040000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 9;
						break;
					case 11:
						if ((0x10000000100000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 10;
						break;
					case 12:
						if ((0x8000000080000L & l) != 0L)
							jjCheckNAdd(8);
						break;
					case 13:
						if ((0x100000001000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 12;
						break;
					case 14:
						if ((0x200000002L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 13;
						break;
					case 15:
						if ((0x4000000040L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 14;
						break;
					case 18:
						if ((0x7fffffe07fffffeL & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAddStates(6, 8);
						break;
					case 20:
						if ((0x7fffffe07fffffeL & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAddStates(3, 5);
						break;
					case 22:
						if ((0x7fffffe07fffffeL & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAddStates(9, 12);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else {
				int i2 = (curChar & 0xff) >> 6;
				long l2 = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 1:
						if ((jjbitVec0[i2] & l2) != 0L)
							jjAddStates(0, 2);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				jjmatchedKind = kind;
				jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = jjnewStateCnt) == (startsAt = 23 - (jjnewStateCnt = startsAt)))
				return curPos;
			try {
				curChar = input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	static final int[] jjnextStates = { 1, 2, 4, 20, 19, 21, 19, 21, 22, 20, 19, 21, 22, };

	/** Token literal values. */
	public static final String[] jjstrLiteralImages = { "", null, null, null, null, null, null, null, null, "\54",
			"\72", "\173", "\175", "\133", "\135", "\42", null, null, };

	/** Lexer state names. */
	public static final String[] lexStateNames = { "DEFAULT", };
	static final long[] jjtoToken = { 0x1fec1L, };
	static final long[] jjtoSkip = { 0x3eL, };
	static protected SimpleCharStream input_stream;
	static private final int[] jjrounds = new int[23];
	static private final int[] jjstateSet = new int[46];
	static protected char curChar;

	/** Constructor. */
	public LexerJJTokenManager(SimpleCharStream stream) {
		if (input_stream != null)
			throw new TokenMgrError(
					"ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.",
					TokenMgrError.STATIC_LEXER_ERROR);
		input_stream = stream;
	}

	/** Constructor. */
	public LexerJJTokenManager(SimpleCharStream stream, int lexState) {
		this(stream);
		SwitchTo(lexState);
	}

	/** Reinitialise parser. */
	static public void ReInit(SimpleCharStream stream) {
		jjmatchedPos = jjnewStateCnt = 0;
		curLexState = defaultLexState;
		input_stream = stream;
		ReInitRounds();
	}

	static private void ReInitRounds() {
		int i;
		jjround = 0x80000001;
		for (i = 23; i-- > 0;)
			jjrounds[i] = 0x80000000;
	}

	/** Reinitialise parser. */
	static public void ReInit(SimpleCharStream stream, int lexState) {
		ReInit(stream);
		SwitchTo(lexState);
	}

	/** Switch to specified lex state. */
	static public void SwitchTo(int lexState) {
		if (lexState >= 1 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
					TokenMgrError.INVALID_LEXICAL_STATE);
		else
			curLexState = lexState;
	}

	static protected Token jjFillToken() {
		final Token t;
		final String curTokenImage;
		final int beginLine;
		final int endLine;
		final int beginColumn;
		final int endColumn;
		String im = jjstrLiteralImages[jjmatchedKind];
		curTokenImage = (im == null) ? input_stream.GetImage() : im;
		beginLine = input_stream.getBeginLine();
		beginColumn = input_stream.getBeginColumn();
		endLine = input_stream.getEndLine();
		endColumn = input_stream.getEndColumn();
		t = Token.newToken(jjmatchedKind, curTokenImage);

		t.beginLine = beginLine;
		t.endLine = endLine;
		t.beginColumn = beginColumn;
		t.endColumn = endColumn;

		return t;
	}

	static int curLexState = 0;
	static int defaultLexState = 0;
	static int jjnewStateCnt;
	static int jjround;
	static int jjmatchedPos;
	static int jjmatchedKind;

	/** Get the next Token. */
	public static Token getNextToken() {
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {
				curChar = input_stream.BeginToken();
			} catch (java.io.IOException e) {
				jjmatchedKind = 0;
				matchedToken = jjFillToken();
				return matchedToken;
			}

			try {
				input_stream.backup(0);
				while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
					curChar = input_stream.BeginToken();
			} catch (java.io.IOException e1) {
				continue EOFLoop;
			}
			jjmatchedKind = 0x7fffffff;
			jjmatchedPos = 0;
			curPos = jjMoveStringLiteralDfa0_0();
			if (jjmatchedKind != 0x7fffffff) {
				if (jjmatchedPos + 1 < curPos)
					input_stream.backup(curPos - jjmatchedPos - 1);
				if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
					matchedToken = jjFillToken();
					return matchedToken;
				} else {
					continue EOFLoop;
				}
			}
			int error_line = input_stream.getEndLine();
			int error_column = input_stream.getEndColumn();
			String error_after = null;
			boolean EOFSeen = false;
			try {
				input_stream.readChar();
				input_stream.backup(1);
			} catch (java.io.IOException e1) {
				EOFSeen = true;
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
				if (curChar == '\n' || curChar == '\r') {
					error_line++;
					error_column = 0;
				} else
					error_column++;
			}
			if (!EOFSeen) {
				input_stream.backup(1);
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
			}
			throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar,
					TokenMgrError.LEXICAL_ERROR);
		}
	}

	static private void jjCheckNAdd(int state) {
		if (jjrounds[state] != jjround) {
			jjstateSet[jjnewStateCnt++] = state;
			jjrounds[state] = jjround;
		}
	}

	static private void jjAddStates(int start, int end) {
		do {
			jjstateSet[jjnewStateCnt++] = jjnextStates[start];
		} while (start++ != end);
	}

	static private void jjCheckNAddTwoStates(int state1, int state2) {
		jjCheckNAdd(state1);
		jjCheckNAdd(state2);
	}

	static private void jjCheckNAddStates(int start, int end) {
		do {
			jjCheckNAdd(jjnextStates[start]);
		} while (start++ != end);
	}

}
