/* Generated By:JavaCC: Do not edit this line. LexerJJConstants.java */
package com.nexon.jsonparser.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerJJConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 6;
  /** RegularExpression Id. */
  int LOGIC_CONSTANT = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULTIPLY = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int LEFT_BRACE = 15;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 16;
  /** RegularExpression Id. */
  int LEFT_SQUARE = 17;
  /** RegularExpression Id. */
  int RIGHT_SQUARE = 18;
  /** RegularExpression Id. */
  int QUOTE = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<INTEGER_CONSTANT>",
    "<LOGIC_CONSTANT>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
